export enum AlertLevel {
  VERT = 'VERT',
  JAUNE = 'JAUNE',
  ROUGE = 'ROUGE',
}

export enum AlertStatus {
  ACTIVE = 'ACTIVE',
  ACQUITTEE = 'ACQUITTEE',
  RESOLUE = 'RESOLUE',
}

export enum AlertKind {
  EAU = 'EAU',
  ALIMENT = 'ALIMENT',
  MORTALITE = 'MORTALITE',
  SURDENSITE = 'SURDENSITE',
  DENSITE = 'DENSITE',
  DENSITE_BATIMENT = 'DENSITE_BATIMENT',
  COHABITATION = 'COHABITATION',
  VIDE_SANITAIRE = 'VIDE_SANITAIRE',
  IPE = 'IPE',
  GMQ = 'GMQ',
  PEREMPTION = 'PEREMPTION',
  TRACABILITE = 'TRACABILITE',
  VENTE = 'VENTE',
  DELAI_ATTENTE = 'DELAI_ATTENTE',
  PROPHYLAXIE = 'PROPHYLAXIE',
}
