export enum ExpenseCategory {
  ACHAT_POUSSINS = 'ACHAT_POUSSINS',
  ALIMENTS = 'ALIMENTS',
  TRAITEMENTS_SANITAIRES = 'TRAITEMENTS_SANITAIRES',
  TRANSPORT = 'TRANSPORT',
  ENERGIE_GAZ = 'ENERGIE_GAZ',
  MAIN_D_OEUVRE = 'MAIN_D_OEUVRE',
  AUTRE = 'AUTRE',
}
