export enum FeedPhase {
  POUSSIN = 'POUSSIN',
  DEMARRAGE = 'DEMARRAGE',
  CROISSANCE = 'CROISSANCE',
  PRE_PONTE = 'PRE_PONTE',
  PONTE_PHASE_1 = 'PONTE_PHASE_1',
  PONTE_PHASE_2 = 'PONTE_PHASE_2',
  PONTE_PHASE_3 = 'PONTE_PHASE_3',
  FINITION = 'FINITION',
  PERSONNALISE = 'PERSONNALISE',
}
